Us 11 contact
WildCodeSchool-2024-02/php-p2-strasgite pull request #14
Opened 2024-04-19 10:43 UTC by Halcomberg

Ajout message personnalisé formulaire de contact avec page result et sa route et ajout icônes bootstrap réseaux sociaux dans le footer.

2024-04-22 21:09 UTC, Dogegab approved these changes

2024-04-23 07:04 UTC, vravanel requested changes
deux trois petits changements et c'est good bien joué !

2024-04-23 07:04 UTC, vravanel commented on EditDB.sql
Pourquoi vous avez deux fichiers sql ?

2024-04-23 07:04 UTC, vravanel commented on database.sql
> +=======
Attention au = qui traîne

2024-04-23 07:04 UTC, vravanel commented on src/View/Include/_footer.html.twig
> +        <img src="#" alt="Insta"> #}
Si ça sert plus il faut l'enlever

2024-04-23 10:22 UTC, Halcomberg commented on src/View/Include/_footer.html.twig
> +        <img src="#" alt="Insta"> #}
Suppression des lignes commentées.

2024-04-23 10:25 UTC, Halcomberg commented on database.sql
> +=======
Les "=" ont été supprimés (je ne sais pas pourquoi ils y étaient sachant que je les vire lors des conflits git)..

2024-04-23 10:42 UTC, Halcomberg commented on EditDB.sql
C'est fait, tout est dans database.sql, editDB supprimé

2024-04-23 10:44 UTC, vravanel approved these changes

2024-04-23 10:44 UTC, merged